[package]
name = "neander_interpreter"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tui-app"
path = "src/tui/interface.rs"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
color-eyre = "0.6.5"
